[physical]
G0 = 6.67430E-11 # m³/(kg·s²)

[simulation]
dim = 2

[simulation.units]
dist = { val = 0.1, unit = "kpc" }
time = { val = 1.0, unit = "Myear" }
mass = { val = 1.0, unit = "mass_sun" }

[simulation.size]
extent = { x = 100, y = 100 }

[simulation.mass_distribution]
type = "simple_exponential"
N = 1000
total_mass = 1E11
lambda = 0.1 # Exponential distribution parameter

[simulation.engine]
type = "tree"
eps = 5 # Plummer potential distance parameter
theta = 0.3 # Tree approximation parameter

[simulation.integration]
type = "leapfrog"
dt = 0.5

[simulation.video]
point_size = 2
size.scale = 3

[simulation.plots.energy]
enable = false
